//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;

namespace FlexWiki.BuildVerificationTests.EditService
{

  /// <remarks/>
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Web.Services.WebServiceBindingAttribute(Name="EditServiceSoap", Namespace="http://www.flexwiki.com/webservices/")]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(TopicName))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReflectedValueSource))]
  public class EditServiceProxy : System.Web.Services.Protocols.SoapHttpClientProtocol 
  {
    
    /// <remarks/>
    public EditServiceProxy() 
    {
      this.Url = "http://localhost/FlexWikiCore/EditService.asmx";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/CanEdit", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CanEdit() 
    {
      object[] results = this.Invoke("CanEdit", new object[0]);
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCanEdit(System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("CanEdit", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndCanEdit(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetAllNamespaces", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ContentBase[] GetAllNamespaces() 
    {
      object[] results = this.Invoke("GetAllNamespaces", new object[0]);
      return ((ContentBase[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAllNamespaces(System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetAllNamespaces", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ContentBase[] EndGetAllNamespaces(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((ContentBase[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetAllTopics", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public AbsoluteTopicName[] GetAllTopics(ContentBase cb) 
    {
      object[] results = this.Invoke("GetAllTopics", new object[] {
                                                                    cb});
      return ((AbsoluteTopicName[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAllTopics(ContentBase cb, System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetAllTopics", new object[] {
                                                             cb}, callback, asyncState);
    }
    
    /// <remarks/>
    public AbsoluteTopicName[] EndGetAllTopics(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((AbsoluteTopicName[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetDefaultNamespace", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ContentBase GetDefaultNamespace() 
    {
      object[] results = this.Invoke("GetDefaultNamespace", new object[0]);
      return ((ContentBase)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDefaultNamespace(System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetDefaultNamespace", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ContentBase EndGetDefaultNamespace(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((ContentBase)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetHtmlForTopic", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetHtmlForTopic(AbsoluteTopicName topicName) 
    {
      object[] results = this.Invoke("GetHtmlForTopic", new object[] {
                                                                       topicName});
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetHtmlForTopic(AbsoluteTopicName topicName, System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetHtmlForTopic", new object[] {
                                                                topicName}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetHtmlForTopic(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetHtmlForTopicVersion", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetHtmlForTopicVersion(AbsoluteTopicName topicName, string version) 
    {
      object[] results = this.Invoke("GetHtmlForTopicVersion", new object[] {
                                                                              topicName,
                                                                              version});
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetHtmlForTopicVersion(AbsoluteTopicName topicName, string version, System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetHtmlForTopicVersion", new object[] {
                                                                       topicName,
                                                                       version}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetHtmlForTopicVersion(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetPreviewForTopic", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetPreviewForTopic(AbsoluteTopicName topicName, string textToFormat) 
    {
      object[] results = this.Invoke("GetPreviewForTopic", new object[] {
                                                                          topicName,
                                                                          textToFormat});
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetPreviewForTopic(AbsoluteTopicName topicName, string textToFormat, System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetPreviewForTopic", new object[] {
                                                                   topicName,
                                                                   textToFormat}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetPreviewForTopic(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetTextForTopic", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetTextForTopic(AbsoluteTopicName topicName) 
    {
      object[] results = this.Invoke("GetTextForTopic", new object[] {
                                                                       topicName});
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTextForTopic(AbsoluteTopicName topicName, System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetTextForTopic", new object[] {
                                                                topicName}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetTextForTopic(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetVersionsForTopic", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] GetVersionsForTopic(AbsoluteTopicName topicName) 
    {
      object[] results = this.Invoke("GetVersionsForTopic", new object[] {
                                                                           topicName});
      return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetVersionsForTopic(AbsoluteTopicName topicName, System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetVersionsForTopic", new object[] {
                                                                    topicName}, callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndGetVersionsForTopic(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((string[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/GetWikiVersion", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public WikiVersion GetWikiVersion() 
    {
      object[] results = this.Invoke("GetWikiVersion", new object[0]);
      return ((WikiVersion)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetWikiVersion(System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("GetWikiVersion", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public WikiVersion EndGetWikiVersion(System.IAsyncResult asyncResult) 
    {
      object[] results = this.EndInvoke(asyncResult);
      return ((WikiVersion)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/RestoreTopic", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RestoreTopic(AbsoluteTopicName topicName, string visitorIdentityString, string version) 
    {
      this.Invoke("RestoreTopic", new object[] {
                                                 topicName,
                                                 visitorIdentityString,
                                                 version});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRestoreTopic(AbsoluteTopicName topicName, string visitorIdentityString, string version, System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("RestoreTopic", new object[] {
                                                             topicName,
                                                             visitorIdentityString,
                                                             version}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndRestoreTopic(System.IAsyncResult asyncResult) 
    {
      this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.flexwiki.com/webservices/SetTextForTopic", RequestNamespace="http://www.flexwiki.com/webservices/", ResponseNamespace="http://www.flexwiki.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SetTextForTopic(AbsoluteTopicName topicName, string postedTopicText, string visitorIdentityString) 
    {
      this.Invoke("SetTextForTopic", new object[] {
                                                    topicName,
                                                    postedTopicText,
                                                    visitorIdentityString});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSetTextForTopic(AbsoluteTopicName topicName, string postedTopicText, string visitorIdentityString, System.AsyncCallback callback, object asyncState) 
    {
      return this.BeginInvoke("SetTextForTopic", new object[] {
                                                                topicName,
                                                                postedTopicText,
                                                                visitorIdentityString}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSetTextForTopic(System.IAsyncResult asyncResult) 
    {
      this.EndInvoke(asyncResult);
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flexwiki.com/webservices/")]
  public class ContentBase : BELObject 
  {
    
    /// <remarks/>
    public System.DateTime Created;
    
    /// <remarks/>
    public System.DateTime LastRead;
    
    /// <remarks/>
    public bool Secure;
    
    /// <remarks/>
    public string Description;
    
    /// <remarks/>
    public string Contact;
    
    /// <remarks/>
    public string ImageURL;
    
    /// <remarks/>
    public string HomePage;
    
    /// <remarks/>
    public bool DisplaySpacesInWikiLinks;
    
    /// <remarks/>
    public string Namespace;
    
    /// <remarks/>
    public string Title;
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flexwiki.com/webservices/")]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentBase))]
  public abstract class BELObject : ReflectedValueSource 
  {
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flexwiki.com/webservices/")]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(BELObject))]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentBase))]
  public abstract class ReflectedValueSource 
  {
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flexwiki.com/webservices/")]
  [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbsoluteTopicName))]
  public abstract class TopicName 
  {
    
    /// <remarks/>
    public string FullnameWithVersion;
    
    /// <remarks/>
    public string Version;
    
    /// <remarks/>
    public string Fullname;
    
    /// <remarks/>
    public string Name;
    
    /// <remarks/>
    public string Namespace;
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.flexwiki.com/webservices/")]
  public class AbsoluteTopicName : TopicName 
  {
  }

  /// <remarks/>
  public class WikiVersion
  {
    private int major; 
    private int minor;
    private int build;
    private int revision; 

    public int Major
    {
      get { return major; }
      set { major = value; }
    }

    public int Minor
    {
      get { return minor; }
      set { minor = value; }
    }

    public int Build
    {
      get { return build; }
      set { build = value; }
    }

    public int Revision
    {
      get { return revision; }
      set { revision = value; }
    }
  }

}